steps:
  - name: gcr.io/cloud-builders/git
    args: ['clone', '-b', '${TAG_NAME}', '--single-branch', '--depth', '1', 'https://github.com/donaldrauscher/djr-py.git']
#  - name: gcr.io/cloud-builders/git
#    args: ['clone', 'https://github.com/donaldrauscher/gcs-pypi.git']
  - name: gcr.io/${PROJECT_ID}/python-packager:latest
    entrypoint: 'bash'
    args: ['-c', 'pip3 install -e . && python3 -m pytest -s']
    dir: '/workspace/djr-py'
  - name: gcr.io/${PROJECT_ID}/python-packager:latest
    args: ['setup.py', 'sdist']
    dir: '/workspace/djr-py'
  - name: gcr.io/cloud-builders/gsutil
    args: ['cp', 'dist/djr-py-${TAG_NAME}.tar.gz', 'gs://pypi.donaldrauscher.com']
    dir: '/workspace/djr-py'
#  - name: gcr.io/cloud-builders/gcloud
#    args: ['builds', 'submit', '--config', 'cloudbuild.yaml', '--no-source', '--async']
#    dir: '/workspace/djr-pypi'