steps:
  - name: gcr.io/cloud-builders/git
    args: ['clone', '-b', '${_BRANCH_NAME}', '--single-branch', '--depth', '1', 'https://github.com/donaldrauscher/djr-py.git']
  - name: gcr.io/${PROJECT_ID}/python-packager:latest
    args: ["sdist", "bdist_wheel"]
    env: ['VERSION=${_TAG_NAME}']
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: gsutil
    args: ["-m", "cp", "-r", "dist", "gs://${_SUB_DOMAIN}.donaldrauscher.com/djr-py"]
substitutions:
  _BRANCH_NAME: master
  _TAG_NAME: '0.1'
  _SUB_DOMAIN: pypi
