steps:
  - name: gcr.io/cloud-builders/git
    args: ['clone', '-b', '${_BRANCH_NAME}', '--single-branch', '--depth', '1', 'https://github.com/donaldrauscher/djr-py.git']
  - name: gcr.io/${PROJECT_ID}/python-packager:latest
    args: ["sdist"]
    env: ['VERSION=${_TAG_NAME}']
  - name: gcr.io/cloud-builders/curl
    args: ["-F", "package=@dist/djr-py-${_TAG_NAME}.tar.gz", "https://${_FURY_TOKEN}@push.fury.io/donaldrauscher/"]
substitutions:
  _BRANCH_NAME: master
  _TAG_NAME: '0.0.2'
